// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vtcE5IyMFOPINGpkpRKd3FLH2vtwwKI',
    appId: '1:208982581762:web:0cb458c6f568de97853d1b',
    messagingSenderId: '208982581762',
    projectId: 'hackathon-2024-21591',
    authDomain: 'hackathon-2024-21591.firebaseapp.com',
    storageBucket: 'hackathon-2024-21591.appspot.com',
    measurementId: 'G-D0ZWVN9J7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqESX1YMoMhPc9IfFXalT849AqFKe0o20',
    appId: '1:208982581762:android:41b47fdfae469a58853d1b',
    messagingSenderId: '208982581762',
    projectId: 'hackathon-2024-21591',
    storageBucket: 'hackathon-2024-21591.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9vtcE5IyMFOPINGpkpRKd3FLH2vtwwKI',
    appId: '1:208982581762:web:0ab4bd735267c647853d1b',
    messagingSenderId: '208982581762',
    projectId: 'hackathon-2024-21591',
    authDomain: 'hackathon-2024-21591.firebaseapp.com',
    storageBucket: 'hackathon-2024-21591.appspot.com',
    measurementId: 'G-2027C7W4WB',
  );
}
